# Generated by Django 5.1.7 on 2025-03-15 05:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id_factura', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id_material', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('punto_reorden', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='OrdenesProduccion',
            fields=[
                ('id_orden_produccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_orden', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosTerminados',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('punto_reorden', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('almacen', models.CharField(max_length=100)),
                ('pasillo', models.CharField(blank=True, max_length=50, null=True)),
                ('rack', models.CharField(blank=True, max_length=50, null=True)),
                ('anaquel', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Operador', 'Operador'), ('Supervisor', 'Supervisor')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesFactura',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.facturas')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionMateriales',
            fields=[
                ('id_asignacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.ordenesproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Inspecciones',
            fields=[
                ('id_inspeccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_inspeccion', models.DateTimeField(auto_now_add=True)),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.proveedores')),
            ],
        ),
        migrations.AddField(
            model_name='facturas',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.proveedores'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.productosterminados')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.ubicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionStock',
            fields=[
                ('id_ubicacion_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.productosterminados')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.ubicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id_transferencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.productosterminados')),
                ('id_ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='almacen.ubicaciones')),
                ('id_ubicacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='almacen.ubicaciones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id_salida', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('Producción', 'Producción'), ('Dañado', 'Dañado'), ('Pérdida', 'Pérdida'), ('Ajuste', 'Ajuste')], max_length=100)),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_orden_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.ordenesproduccion')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.productosterminados')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Mermas',
            fields=[
                ('id_merma', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_merma', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=100)),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.productosterminados')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMovimientos',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Transferencia', 'Transferencia'), ('Ajuste', 'Ajuste')], max_length=50)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.productosterminados')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id_entrada', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('factura', models.CharField(blank=True, max_length=100, null=True)),
                ('inspeccionado', models.BooleanField(default=False)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.proveedores')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.ubicaciones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='AjustesInventario',
            fields=[
                ('id_ajuste', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_ajuste', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=100)),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.materiales')),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.productosterminados')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.usuarios')),
            ],
        ),
    ]
